import React from 'react';

const roiData = [
  {
    image: '/sampangi/sampangi-infra-agri-filed-605-sq-yds-750x499.jpg',
    title: '605 SQ YDS Investment',
    income: 'Income on Fruits From 3rd year onwards 20K per year approx',
    dates: 'Income on Dates From 4th Year onwards',
    points: [
      'Drip irrigation system is pre-installed in the plot.',
      'Free maintenance for 15 years',
      'The income generated by selling Fruits & Dates in the market will be shared on 50-50 basis.',
      'Free resort membership with facility to stay in the rooms for 4 days in a year.',
    ],
  },
  {
    image: '/sampangi/sampangi-infra-agri-filed-half-acre-750x499.jpg',
    title: 'Half Acre Investment',
    income: 'Income on Fruits From 3rd year onwards 80K per year approx',
    dates: 'Income on Dates From 4th Year onwards',
    points: [
      'Drip irrigation system is pre-installed in the plot.',
      'Free maintenance for 15 years',
      'Plot owners get Income on harvest of Dates from 4th year onwards.',
      'The income generated by selling dates in the market will be shared on 50-50 basis.',
      'Free resort membership with facility to stay in the rooms for 7 days in a year.',
    ],
  },
  {
    image: '/sampangi/sampangi-infra-agri-filed-one-acre-750x499.jpg',
    title: 'One Acre Investment',
    income: 'Income on Fruits From 3rd year onwards 1.60L per year approx',
    dates: 'Income on Dates From 4th Year onwards',
    points: [
      'Drip irrigation system is pre-installed in the plot.',
      'Free maintenance for 15 years',
      'Plot owners get Income on harvest of Dates from 4th year onwards.',
      'The income generated by selling dates in the market will be shared on 50-50 basis.',
      'Free resort membership with facility to stay in the rooms for 11 days in a year.',
    ],
  },
];

const ReturnOnInvestment = () => {
  return (
    <div className="bg-[#f5f5f5] py-10">
      <h2 className="text-3xl font-semibold text-center text-[#222] mb-3">
        Know Your Return on Investment (ROI)
      </h2>

      {/* Decorative Red Lines */}
      <div className="flex justify-center mb-6">
        <div className="w-6 h-1 bg-red-500 mx-1"></div>
        <div className="w-3 h-1 bg-red-500 mx-1"></div>
        <div className="w-6 h-1 bg-red-500 mx-1"></div>
      </div>

      <div className="flex flex-col md:flex-row justify-center items-stretch gap-6 px-4">
        {roiData.map((item, index) => (
          <div key={index} className="bg-white shadow-md rounded-lg overflow-hidden w-full md:w-1/3 p-4">
            <img src={item.image} alt="ROI Option" className="w-full h-48 object-cover rounded" />
            <div className="mt-4 text-center">
              <p className="text-sm font-semibold text-gray-700">Return on Investment (ROI)</p>
              <h3 className="text-lg font-bold text-black mt-1">{item.title}</h3>

              <div className="text-red-600 font-semibold mt-2">Income Calculation<br />For 15 years 🔗</div>

              <p className="font-bold text-[14px] mt-2">Get 2 Types of Returns</p>

              <ul className="text-left text-sm mt-2 space-y-2">
                <li className="text-black">• {item.income}</li>
                <li className="text-black">• {item.dates}</li>
                {item.points.map((point, idx) => (
                  <li key={idx} className="text-red-600">✘ {point}</li>
                ))}
              </ul>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReturnOnInvestment;
